name: Python Selenium Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest  # You can use windows-latest if preferred

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.13
        uses: actions/setup-python@v2
        with:
          python-version: 3.13

      - name: Install dependencies
        run: |
          python -m venv venv
          . venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt  # Make sure pytest is installed here

      - name: Run tests
        run: |
          . venv/bin/activate
          pytest ./Tests
