name: Python Selenium Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest  # You can change to windows-latest if preferred

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.13
        uses: actions/setup-python@v2
        with:
          python-version: 3.13

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate  # Use venv\Scripts\activate for Windows runners
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          source venv/bin/activate  # Activate the virtual environment again
          python -m pytest ./Tests  # Use python -m pytest to run the tests
